services:
##############################################################################
  pdf_extractor:
##############################################################################
    container_name: pdf_extractor
    build:
      context: .
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - type: bind
        target: /app/OUTPUT_tables
      - type: bind
        source: ./INPUT_pdf_to_scan
        target: /app/INPUT_pdf_to_scan
